# Generated by Django 2.1 on 2018-09-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='yenifield',
            field=models.CharField(blank=True, choices=[('famished', 'Famished'), ('starving', 'Starving'), ('satisfied', 'Satisfied')], max_length=20, null=True),
        ),
    ]
