# Generated by Django 2.1 on 2018-09-06 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_condition_yenifield'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_conds', to='common.Profile'),
        ),
    ]
